<?xml version="1.0" encoding="utf-8"?><Database Name="QLKho" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=QLKho;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="QLKho.Properties.Settings" SettingsPropertyName="QLKhoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.kho" Member="khos">
    <Type Name="kho">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_kho" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hien_thi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ghi_chu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nguoi_tao" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="cap_nhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="kho_nhap_kho" Member="nhap_khos" ThisKey="id" OtherKey="kho_id" Type="nhap_kho" />
    </Type>
  </Table>
  <Table Name="dbo.ncc" Member="nccs">
    <Type Name="ncc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_ncc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hien_thi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ten_day_du" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="loai_ncc" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="logo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nguoi_dai_dien" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tinh_trang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nv_phu_trach" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ghi_chu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngay_cap_nhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ncc_nhap_kho" Member="nhap_khos" ThisKey="id" OtherKey="ncc_id" Type="nhap_kho" />
    </Type>
  </Table>
  <Table Name="dbo.nhap_kho" Member="nhap_khos">
    <Type Name="nhap_kho">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="loai_nhap" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_nhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ncc_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kho_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_nhap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nguoi_giao" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="noi_dung_nhap" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ngay_cap_nhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoi_tao" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="nhap_kho_nhap_kho_ct" Member="nhap_kho_cts" ThisKey="id" OtherKey="nhap_kho_id" Type="nhap_kho_ct" />
      <Association Name="kho_nhap_kho" Member="kho" ThisKey="kho_id" OtherKey="id" Type="kho" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="ncc_nhap_kho" Member="ncc" ThisKey="ncc_id" OtherKey="id" Type="ncc" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.nhap_kho_ct" Member="nhap_kho_cts">
    <Type Name="nhap_kho_ct">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nhap_kho_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngay_nhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="san_pham_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nhom_san_pham" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="hang_sx" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="hinh_anh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="thong_tin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="han_su_dung" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="quy_cach" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="dvt" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="so_lo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="gia_nhap" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="sl_nhap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_xuat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_ton" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngay_het_han" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ghi_chu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngay_cap_nhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nguoi_tao" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="nhap_kho_nhap_kho_ct" Member="nhap_kho" ThisKey="nhap_kho_id" OtherKey="id" Type="nhap_kho" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="san_pham_nhap_kho_ct" Member="san_pham" ThisKey="san_pham_id" OtherKey="id" Type="san_pham" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.xuat_kho" Member="xuat_khos">
    <Type Name="xuat_kho">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="loat_xuat" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_xuat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nhan_vien_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ma_hoa_don" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="sl_san_pham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_xuat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="noi_dung_xuat" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ghi_chu" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngay_cap_nhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nguoi_tao" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="xuat_kho_xuat_kho_ct" Member="xuat_kho_cts" ThisKey="id" OtherKey="xuat_kho_id" Type="xuat_kho_ct" />
    </Type>
  </Table>
  <Table Name="dbo.san_pham" Member="san_phams">
    <Type Name="san_pham">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_san_pham" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="hien_thi" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nhom_san_pham" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="hang_sx" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="hinh_anh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dia_chi" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="thong_tin" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="han_su_dung" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="quy_cach" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="dvt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gia_nhap" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="sl_toi_thieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_toi_da" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_nhap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_xuat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_ton" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="trang_thai" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ghi_chu" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngay_cap_nhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nguoi_tao" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="san_pham_nhap_kho_ct" Member="nhap_kho_cts" ThisKey="id" OtherKey="san_pham_id" Type="nhap_kho_ct" />
      <Association Name="san_pham_xuat_kho_ct" Member="xuat_kho_cts" ThisKey="id" OtherKey="san_pham_id" Type="xuat_kho_ct" />
    </Type>
  </Table>
  <Table Name="dbo.thong_tin_cty" Member="thong_tin_cties">
    <Type Name="thong_tin_cty">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_cty" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ten_day_du" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nguoi_dai_dien" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dia_chi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="website" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngay_update" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.xuat_kho_ct" Member="xuat_kho_cts">
    <Type Name="xuat_kho_ct">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoaiXuat" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="xuat_kho_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngay_xuat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="san_pham_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_san_pham" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nhom_san_pham" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="hang_sx" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="hinh_anh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="thong_tin" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="quy_cach" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="dvt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="so_lo" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_het_han" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sl_xuat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sl_xuat_tong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngay_cap_nhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nguoi_tao" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="san_pham_xuat_kho_ct" Member="san_pham" ThisKey="san_pham_id" OtherKey="id" Type="san_pham" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="xuat_kho_xuat_kho_ct" Member="xuat_kho" ThisKey="xuat_kho_id" OtherKey="id" Type="xuat_kho" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>