#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKho
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKho")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkho(kho instance);
    partial void Updatekho(kho instance);
    partial void Deletekho(kho instance);
    partial void Insertncc(ncc instance);
    partial void Updatencc(ncc instance);
    partial void Deletencc(ncc instance);
    partial void Insertnhap_kho(nhap_kho instance);
    partial void Updatenhap_kho(nhap_kho instance);
    partial void Deletenhap_kho(nhap_kho instance);
    partial void Insertnhap_kho_ct(nhap_kho_ct instance);
    partial void Updatenhap_kho_ct(nhap_kho_ct instance);
    partial void Deletenhap_kho_ct(nhap_kho_ct instance);
    partial void Insertxuat_kho(xuat_kho instance);
    partial void Updatexuat_kho(xuat_kho instance);
    partial void Deletexuat_kho(xuat_kho instance);
    partial void Insertsan_pham(san_pham instance);
    partial void Updatesan_pham(san_pham instance);
    partial void Deletesan_pham(san_pham instance);
    partial void Insertthong_tin_cty(thong_tin_cty instance);
    partial void Updatethong_tin_cty(thong_tin_cty instance);
    partial void Deletethong_tin_cty(thong_tin_cty instance);
    partial void Insertxuat_kho_ct(xuat_kho_ct instance);
    partial void Updatexuat_kho_ct(xuat_kho_ct instance);
    partial void Deletexuat_kho_ct(xuat_kho_ct instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QLKho.Properties.Settings.Default.QLKhoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kho> khos
		{
			get
			{
				return this.GetTable<kho>();
			}
		}
		
		public System.Data.Linq.Table<ncc> nccs
		{
			get
			{
				return this.GetTable<ncc>();
			}
		}
		
		public System.Data.Linq.Table<nhap_kho> nhap_khos
		{
			get
			{
				return this.GetTable<nhap_kho>();
			}
		}
		
		public System.Data.Linq.Table<nhap_kho_ct> nhap_kho_cts
		{
			get
			{
				return this.GetTable<nhap_kho_ct>();
			}
		}
		
		public System.Data.Linq.Table<xuat_kho> xuat_khos
		{
			get
			{
				return this.GetTable<xuat_kho>();
			}
		}
		
		public System.Data.Linq.Table<san_pham> san_phams
		{
			get
			{
				return this.GetTable<san_pham>();
			}
		}
		
		public System.Data.Linq.Table<thong_tin_cty> thong_tin_cties
		{
			get
			{
				return this.GetTable<thong_tin_cty>();
			}
		}
		
		public System.Data.Linq.Table<xuat_kho_ct> xuat_kho_cts
		{
			get
			{
				return this.GetTable<xuat_kho_ct>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kho")]
	public partial class kho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten_kho;
		
		private string _hien_thi;
		
		private string _ghi_chu;
		
		private string _nguoi_tao;
		
		private System.DateTime _ngay_tao;
		
		private System.DateTime _cap_nhat;
		
		private EntitySet<nhap_kho> _nhap_khos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onten_khoChanging(string value);
    partial void Onten_khoChanged();
    partial void Onhien_thiChanging(string value);
    partial void Onhien_thiChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onnguoi_taoChanging(string value);
    partial void Onnguoi_taoChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Oncap_nhatChanging(System.DateTime value);
    partial void Oncap_nhatChanged();
    #endregion
		
		public kho()
		{
			this._nhap_khos = new EntitySet<nhap_kho>(new Action<nhap_kho>(this.attach_nhap_khos), new Action<nhap_kho>(this.detach_nhap_khos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_kho", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_kho
		{
			get
			{
				return this._ten_kho;
			}
			set
			{
				if ((this._ten_kho != value))
				{
					this.Onten_khoChanging(value);
					this.SendPropertyChanging();
					this._ten_kho = value;
					this.SendPropertyChanged("ten_kho");
					this.Onten_khoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hien_thi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hien_thi
		{
			get
			{
				return this._hien_thi;
			}
			set
			{
				if ((this._hien_thi != value))
				{
					this.Onhien_thiChanging(value);
					this.SendPropertyChanging();
					this._hien_thi = value;
					this.SendPropertyChanged("hien_thi");
					this.Onhien_thiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_tao", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nguoi_tao
		{
			get
			{
				return this._nguoi_tao;
			}
			set
			{
				if ((this._nguoi_tao != value))
				{
					this.Onnguoi_taoChanging(value);
					this.SendPropertyChanging();
					this._nguoi_tao = value;
					this.SendPropertyChanged("nguoi_tao");
					this.Onnguoi_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cap_nhat", DbType="DateTime NOT NULL")]
		public System.DateTime cap_nhat
		{
			get
			{
				return this._cap_nhat;
			}
			set
			{
				if ((this._cap_nhat != value))
				{
					this.Oncap_nhatChanging(value);
					this.SendPropertyChanging();
					this._cap_nhat = value;
					this.SendPropertyChanged("cap_nhat");
					this.Oncap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kho_nhap_kho", Storage="_nhap_khos", ThisKey="id", OtherKey="kho_id")]
		public EntitySet<nhap_kho> nhap_khos
		{
			get
			{
				return this._nhap_khos;
			}
			set
			{
				this._nhap_khos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhap_khos(nhap_kho entity)
		{
			this.SendPropertyChanging();
			entity.kho = this;
		}
		
		private void detach_nhap_khos(nhap_kho entity)
		{
			this.SendPropertyChanging();
			entity.kho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ncc")]
	public partial class ncc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten_ncc;
		
		private string _hien_thi;
		
		private string _ten_day_du;
		
		private string _loai_ncc;
		
		private string _logo;
		
		private string _nguoi_dai_dien;
		
		private string _sdt;
		
		private string _tinh_trang;
		
		private string _nv_phu_trach;
		
		private string _ghi_chu;
		
		private System.DateTime _ngay_tao;
		
		private System.DateTime _ngay_cap_nhat;
		
		private EntitySet<nhap_kho> _nhap_khos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onten_nccChanging(string value);
    partial void Onten_nccChanged();
    partial void Onhien_thiChanging(string value);
    partial void Onhien_thiChanged();
    partial void Onten_day_duChanging(string value);
    partial void Onten_day_duChanged();
    partial void Onloai_nccChanging(string value);
    partial void Onloai_nccChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void Onnguoi_dai_dienChanging(string value);
    partial void Onnguoi_dai_dienChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void Ontinh_trangChanging(string value);
    partial void Ontinh_trangChanged();
    partial void Onnv_phu_trachChanging(string value);
    partial void Onnv_phu_trachChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.DateTime value);
    partial void Onngay_cap_nhatChanged();
    #endregion
		
		public ncc()
		{
			this._nhap_khos = new EntitySet<nhap_kho>(new Action<nhap_kho>(this.attach_nhap_khos), new Action<nhap_kho>(this.detach_nhap_khos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_ncc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_ncc
		{
			get
			{
				return this._ten_ncc;
			}
			set
			{
				if ((this._ten_ncc != value))
				{
					this.Onten_nccChanging(value);
					this.SendPropertyChanging();
					this._ten_ncc = value;
					this.SendPropertyChanged("ten_ncc");
					this.Onten_nccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hien_thi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hien_thi
		{
			get
			{
				return this._hien_thi;
			}
			set
			{
				if ((this._hien_thi != value))
				{
					this.Onhien_thiChanging(value);
					this.SendPropertyChanging();
					this._hien_thi = value;
					this.SendPropertyChanged("hien_thi");
					this.Onhien_thiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_day_du", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_day_du
		{
			get
			{
				return this._ten_day_du;
			}
			set
			{
				if ((this._ten_day_du != value))
				{
					this.Onten_day_duChanging(value);
					this.SendPropertyChanging();
					this._ten_day_du = value;
					this.SendPropertyChanged("ten_day_du");
					this.Onten_day_duChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_ncc", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string loai_ncc
		{
			get
			{
				return this._loai_ncc;
			}
			set
			{
				if ((this._loai_ncc != value))
				{
					this.Onloai_nccChanging(value);
					this.SendPropertyChanging();
					this._loai_ncc = value;
					this.SendPropertyChanged("loai_ncc");
					this.Onloai_nccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dai_dien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nguoi_dai_dien
		{
			get
			{
				return this._nguoi_dai_dien;
			}
			set
			{
				if ((this._nguoi_dai_dien != value))
				{
					this.Onnguoi_dai_dienChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dai_dien = value;
					this.SendPropertyChanged("nguoi_dai_dien");
					this.Onnguoi_dai_dienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinh_trang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tinh_trang
		{
			get
			{
				return this._tinh_trang;
			}
			set
			{
				if ((this._tinh_trang != value))
				{
					this.Ontinh_trangChanging(value);
					this.SendPropertyChanging();
					this._tinh_trang = value;
					this.SendPropertyChanged("tinh_trang");
					this.Ontinh_trangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nv_phu_trach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nv_phu_trach
		{
			get
			{
				return this._nv_phu_trach;
			}
			set
			{
				if ((this._nv_phu_trach != value))
				{
					this.Onnv_phu_trachChanging(value);
					this.SendPropertyChanging();
					this._nv_phu_trach = value;
					this.SendPropertyChanged("nv_phu_trach");
					this.Onnv_phu_trachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ncc_nhap_kho", Storage="_nhap_khos", ThisKey="id", OtherKey="ncc_id")]
		public EntitySet<nhap_kho> nhap_khos
		{
			get
			{
				return this._nhap_khos;
			}
			set
			{
				this._nhap_khos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhap_khos(nhap_kho entity)
		{
			this.SendPropertyChanging();
			entity.ncc = this;
		}
		
		private void detach_nhap_khos(nhap_kho entity)
		{
			this.SendPropertyChanging();
			entity.ncc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhap_kho")]
	public partial class nhap_kho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _loai_nhap;
		
		private System.DateTime _ngay_nhap;
		
		private int _ncc_id;
		
		private int _kho_id;
		
		private int _sl_nhap;
		
		private string _nguoi_giao;
		
		private string _noi_dung_nhap;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhat;
		
		private string _nguoi_tao;
		
		private EntitySet<nhap_kho_ct> _nhap_kho_cts;
		
		private EntityRef<kho> _kho;
		
		private EntityRef<ncc> _ncc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onloai_nhapChanging(string value);
    partial void Onloai_nhapChanged();
    partial void Onngay_nhapChanging(System.DateTime value);
    partial void Onngay_nhapChanged();
    partial void Onncc_idChanging(int value);
    partial void Onncc_idChanged();
    partial void Onkho_idChanging(int value);
    partial void Onkho_idChanged();
    partial void Onsl_nhapChanging(int value);
    partial void Onsl_nhapChanged();
    partial void Onnguoi_giaoChanging(string value);
    partial void Onnguoi_giaoChanged();
    partial void Onnoi_dung_nhapChanging(string value);
    partial void Onnoi_dung_nhapChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhatChanged();
    partial void Onnguoi_taoChanging(string value);
    partial void Onnguoi_taoChanged();
    #endregion
		
		public nhap_kho()
		{
			this._nhap_kho_cts = new EntitySet<nhap_kho_ct>(new Action<nhap_kho_ct>(this.attach_nhap_kho_cts), new Action<nhap_kho_ct>(this.detach_nhap_kho_cts));
			this._kho = default(EntityRef<kho>);
			this._ncc = default(EntityRef<ncc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_nhap", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string loai_nhap
		{
			get
			{
				return this._loai_nhap;
			}
			set
			{
				if ((this._loai_nhap != value))
				{
					this.Onloai_nhapChanging(value);
					this.SendPropertyChanging();
					this._loai_nhap = value;
					this.SendPropertyChanged("loai_nhap");
					this.Onloai_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_nhap", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_nhap
		{
			get
			{
				return this._ngay_nhap;
			}
			set
			{
				if ((this._ngay_nhap != value))
				{
					this.Onngay_nhapChanging(value);
					this.SendPropertyChanging();
					this._ngay_nhap = value;
					this.SendPropertyChanged("ngay_nhap");
					this.Onngay_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ncc_id", DbType="Int NOT NULL")]
		public int ncc_id
		{
			get
			{
				return this._ncc_id;
			}
			set
			{
				if ((this._ncc_id != value))
				{
					if (this._ncc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onncc_idChanging(value);
					this.SendPropertyChanging();
					this._ncc_id = value;
					this.SendPropertyChanged("ncc_id");
					this.Onncc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kho_id", DbType="Int NOT NULL")]
		public int kho_id
		{
			get
			{
				return this._kho_id;
			}
			set
			{
				if ((this._kho_id != value))
				{
					if (this._kho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkho_idChanging(value);
					this.SendPropertyChanging();
					this._kho_id = value;
					this.SendPropertyChanged("kho_id");
					this.Onkho_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_nhap", DbType="Int NOT NULL")]
		public int sl_nhap
		{
			get
			{
				return this._sl_nhap;
			}
			set
			{
				if ((this._sl_nhap != value))
				{
					this.Onsl_nhapChanging(value);
					this.SendPropertyChanging();
					this._sl_nhap = value;
					this.SendPropertyChanged("sl_nhap");
					this.Onsl_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_giao", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nguoi_giao
		{
			get
			{
				return this._nguoi_giao;
			}
			set
			{
				if ((this._nguoi_giao != value))
				{
					this.Onnguoi_giaoChanging(value);
					this.SendPropertyChanging();
					this._nguoi_giao = value;
					this.SendPropertyChanged("nguoi_giao");
					this.Onnguoi_giaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noi_dung_nhap", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string noi_dung_nhap
		{
			get
			{
				return this._noi_dung_nhap;
			}
			set
			{
				if ((this._noi_dung_nhap != value))
				{
					this.Onnoi_dung_nhapChanging(value);
					this.SendPropertyChanging();
					this._noi_dung_nhap = value;
					this.SendPropertyChanged("noi_dung_nhap");
					this.Onnoi_dung_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_tao", DbType="NVarChar(255)")]
		public string nguoi_tao
		{
			get
			{
				return this._nguoi_tao;
			}
			set
			{
				if ((this._nguoi_tao != value))
				{
					this.Onnguoi_taoChanging(value);
					this.SendPropertyChanging();
					this._nguoi_tao = value;
					this.SendPropertyChanged("nguoi_tao");
					this.Onnguoi_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhap_kho_nhap_kho_ct", Storage="_nhap_kho_cts", ThisKey="id", OtherKey="nhap_kho_id")]
		public EntitySet<nhap_kho_ct> nhap_kho_cts
		{
			get
			{
				return this._nhap_kho_cts;
			}
			set
			{
				this._nhap_kho_cts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kho_nhap_kho", Storage="_kho", ThisKey="kho_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public kho kho
		{
			get
			{
				return this._kho.Entity;
			}
			set
			{
				kho previousValue = this._kho.Entity;
				if (((previousValue != value) 
							|| (this._kho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kho.Entity = null;
						previousValue.nhap_khos.Remove(this);
					}
					this._kho.Entity = value;
					if ((value != null))
					{
						value.nhap_khos.Add(this);
						this._kho_id = value.id;
					}
					else
					{
						this._kho_id = default(int);
					}
					this.SendPropertyChanged("kho");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ncc_nhap_kho", Storage="_ncc", ThisKey="ncc_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public ncc ncc
		{
			get
			{
				return this._ncc.Entity;
			}
			set
			{
				ncc previousValue = this._ncc.Entity;
				if (((previousValue != value) 
							|| (this._ncc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ncc.Entity = null;
						previousValue.nhap_khos.Remove(this);
					}
					this._ncc.Entity = value;
					if ((value != null))
					{
						value.nhap_khos.Add(this);
						this._ncc_id = value.id;
					}
					else
					{
						this._ncc_id = default(int);
					}
					this.SendPropertyChanged("ncc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhap_kho_cts(nhap_kho_ct entity)
		{
			this.SendPropertyChanging();
			entity.nhap_kho = this;
		}
		
		private void detach_nhap_kho_cts(nhap_kho_ct entity)
		{
			this.SendPropertyChanging();
			entity.nhap_kho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhap_kho_ct")]
	public partial class nhap_kho_ct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _nhap_kho_id;
		
		private System.DateTime _ngay_nhap;
		
		private int _san_pham_id;
		
		private string _nhom_san_pham;
		
		private string _hang_sx;
		
		private string _hinh_anh;
		
		private string _thong_tin;
		
		private System.DateTime _han_su_dung;
		
		private string _quy_cach;
		
		private string _dvt;
		
		private string _so_lo;
		
		private double _gia_nhap;
		
		private int _sl_nhap;
		
		private int _sl_xuat;
		
		private int _sl_ton;
		
		private System.DateTime _ngay_het_han;
		
		private string _ghi_chu;
		
		private System.DateTime _ngay_tao;
		
		private System.DateTime _ngay_cap_nhat;
		
		private string _nguoi_tao;
		
		private EntityRef<nhap_kho> _nhap_kho;
		
		private EntityRef<san_pham> _san_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnhap_kho_idChanging(int value);
    partial void Onnhap_kho_idChanged();
    partial void Onngay_nhapChanging(System.DateTime value);
    partial void Onngay_nhapChanged();
    partial void Onsan_pham_idChanging(int value);
    partial void Onsan_pham_idChanged();
    partial void Onnhom_san_phamChanging(string value);
    partial void Onnhom_san_phamChanged();
    partial void Onhang_sxChanging(string value);
    partial void Onhang_sxChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    partial void Onthong_tinChanging(string value);
    partial void Onthong_tinChanged();
    partial void Onhan_su_dungChanging(System.DateTime value);
    partial void Onhan_su_dungChanged();
    partial void Onquy_cachChanging(string value);
    partial void Onquy_cachChanged();
    partial void OndvtChanging(string value);
    partial void OndvtChanged();
    partial void Onso_loChanging(string value);
    partial void Onso_loChanged();
    partial void Ongia_nhapChanging(double value);
    partial void Ongia_nhapChanged();
    partial void Onsl_nhapChanging(int value);
    partial void Onsl_nhapChanged();
    partial void Onsl_xuatChanging(int value);
    partial void Onsl_xuatChanged();
    partial void Onsl_tonChanging(int value);
    partial void Onsl_tonChanged();
    partial void Onngay_het_hanChanging(System.DateTime value);
    partial void Onngay_het_hanChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.DateTime value);
    partial void Onngay_cap_nhatChanged();
    partial void Onnguoi_taoChanging(string value);
    partial void Onnguoi_taoChanged();
    #endregion
		
		public nhap_kho_ct()
		{
			this._nhap_kho = default(EntityRef<nhap_kho>);
			this._san_pham = default(EntityRef<san_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhap_kho_id", DbType="Int NOT NULL")]
		public int nhap_kho_id
		{
			get
			{
				return this._nhap_kho_id;
			}
			set
			{
				if ((this._nhap_kho_id != value))
				{
					if (this._nhap_kho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnhap_kho_idChanging(value);
					this.SendPropertyChanging();
					this._nhap_kho_id = value;
					this.SendPropertyChanged("nhap_kho_id");
					this.Onnhap_kho_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_nhap", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_nhap
		{
			get
			{
				return this._ngay_nhap;
			}
			set
			{
				if ((this._ngay_nhap != value))
				{
					this.Onngay_nhapChanging(value);
					this.SendPropertyChanging();
					this._ngay_nhap = value;
					this.SendPropertyChanged("ngay_nhap");
					this.Onngay_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="Int NOT NULL")]
		public int san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhom_san_pham", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nhom_san_pham
		{
			get
			{
				return this._nhom_san_pham;
			}
			set
			{
				if ((this._nhom_san_pham != value))
				{
					this.Onnhom_san_phamChanging(value);
					this.SendPropertyChanging();
					this._nhom_san_pham = value;
					this.SendPropertyChanged("nhom_san_pham");
					this.Onnhom_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hang_sx", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string hang_sx
		{
			get
			{
				return this._hang_sx;
			}
			set
			{
				if ((this._hang_sx != value))
				{
					this.Onhang_sxChanging(value);
					this.SendPropertyChanging();
					this._hang_sx = value;
					this.SendPropertyChanged("hang_sx");
					this.Onhang_sxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thong_tin", DbType="NVarChar(100)")]
		public string thong_tin
		{
			get
			{
				return this._thong_tin;
			}
			set
			{
				if ((this._thong_tin != value))
				{
					this.Onthong_tinChanging(value);
					this.SendPropertyChanging();
					this._thong_tin = value;
					this.SendPropertyChanged("thong_tin");
					this.Onthong_tinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_han_su_dung", DbType="DateTime NOT NULL")]
		public System.DateTime han_su_dung
		{
			get
			{
				return this._han_su_dung;
			}
			set
			{
				if ((this._han_su_dung != value))
				{
					this.Onhan_su_dungChanging(value);
					this.SendPropertyChanging();
					this._han_su_dung = value;
					this.SendPropertyChanged("han_su_dung");
					this.Onhan_su_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quy_cach", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string quy_cach
		{
			get
			{
				return this._quy_cach;
			}
			set
			{
				if ((this._quy_cach != value))
				{
					this.Onquy_cachChanging(value);
					this.SendPropertyChanging();
					this._quy_cach = value;
					this.SendPropertyChanged("quy_cach");
					this.Onquy_cachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dvt", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string dvt
		{
			get
			{
				return this._dvt;
			}
			set
			{
				if ((this._dvt != value))
				{
					this.OndvtChanging(value);
					this.SendPropertyChanging();
					this._dvt = value;
					this.SendPropertyChanged("dvt");
					this.OndvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_lo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string so_lo
		{
			get
			{
				return this._so_lo;
			}
			set
			{
				if ((this._so_lo != value))
				{
					this.Onso_loChanging(value);
					this.SendPropertyChanging();
					this._so_lo = value;
					this.SendPropertyChanged("so_lo");
					this.Onso_loChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_nhap", DbType="Float NOT NULL")]
		public double gia_nhap
		{
			get
			{
				return this._gia_nhap;
			}
			set
			{
				if ((this._gia_nhap != value))
				{
					this.Ongia_nhapChanging(value);
					this.SendPropertyChanging();
					this._gia_nhap = value;
					this.SendPropertyChanged("gia_nhap");
					this.Ongia_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_nhap", DbType="Int NOT NULL")]
		public int sl_nhap
		{
			get
			{
				return this._sl_nhap;
			}
			set
			{
				if ((this._sl_nhap != value))
				{
					this.Onsl_nhapChanging(value);
					this.SendPropertyChanging();
					this._sl_nhap = value;
					this.SendPropertyChanged("sl_nhap");
					this.Onsl_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_xuat", DbType="Int NOT NULL")]
		public int sl_xuat
		{
			get
			{
				return this._sl_xuat;
			}
			set
			{
				if ((this._sl_xuat != value))
				{
					this.Onsl_xuatChanging(value);
					this.SendPropertyChanging();
					this._sl_xuat = value;
					this.SendPropertyChanged("sl_xuat");
					this.Onsl_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_ton", DbType="Int NOT NULL")]
		public int sl_ton
		{
			get
			{
				return this._sl_ton;
			}
			set
			{
				if ((this._sl_ton != value))
				{
					this.Onsl_tonChanging(value);
					this.SendPropertyChanging();
					this._sl_ton = value;
					this.SendPropertyChanged("sl_ton");
					this.Onsl_tonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_het_han", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_het_han
		{
			get
			{
				return this._ngay_het_han;
			}
			set
			{
				if ((this._ngay_het_han != value))
				{
					this.Onngay_het_hanChanging(value);
					this.SendPropertyChanging();
					this._ngay_het_han = value;
					this.SendPropertyChanged("ngay_het_han");
					this.Onngay_het_hanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_tao", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nguoi_tao
		{
			get
			{
				return this._nguoi_tao;
			}
			set
			{
				if ((this._nguoi_tao != value))
				{
					this.Onnguoi_taoChanging(value);
					this.SendPropertyChanging();
					this._nguoi_tao = value;
					this.SendPropertyChanged("nguoi_tao");
					this.Onnguoi_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhap_kho_nhap_kho_ct", Storage="_nhap_kho", ThisKey="nhap_kho_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public nhap_kho nhap_kho
		{
			get
			{
				return this._nhap_kho.Entity;
			}
			set
			{
				nhap_kho previousValue = this._nhap_kho.Entity;
				if (((previousValue != value) 
							|| (this._nhap_kho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhap_kho.Entity = null;
						previousValue.nhap_kho_cts.Remove(this);
					}
					this._nhap_kho.Entity = value;
					if ((value != null))
					{
						value.nhap_kho_cts.Add(this);
						this._nhap_kho_id = value.id;
					}
					else
					{
						this._nhap_kho_id = default(int);
					}
					this.SendPropertyChanged("nhap_kho");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_nhap_kho_ct", Storage="_san_pham", ThisKey="san_pham_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.nhap_kho_cts.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.nhap_kho_cts.Add(this);
						this._san_pham_id = value.id;
					}
					else
					{
						this._san_pham_id = default(int);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xuat_kho")]
	public partial class xuat_kho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _loat_xuat;
		
		private System.DateTime _ngay_xuat;
		
		private int _nhan_vien_id;
		
		private string _ma_hoa_don;
		
		private int _sl_san_pham;
		
		private int _sl_xuat;
		
		private string _noi_dung_xuat;
		
		private string _ghi_chu;
		
		private System.DateTime _ngay_tao;
		
		private System.DateTime _ngay_cap_nhat;
		
		private string _nguoi_tao;
		
		private EntitySet<xuat_kho_ct> _xuat_kho_cts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onloat_xuatChanging(string value);
    partial void Onloat_xuatChanged();
    partial void Onngay_xuatChanging(System.DateTime value);
    partial void Onngay_xuatChanged();
    partial void Onnhan_vien_idChanging(int value);
    partial void Onnhan_vien_idChanged();
    partial void Onma_hoa_donChanging(string value);
    partial void Onma_hoa_donChanged();
    partial void Onsl_san_phamChanging(int value);
    partial void Onsl_san_phamChanged();
    partial void Onsl_xuatChanging(int value);
    partial void Onsl_xuatChanged();
    partial void Onnoi_dung_xuatChanging(string value);
    partial void Onnoi_dung_xuatChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.DateTime value);
    partial void Onngay_cap_nhatChanged();
    partial void Onnguoi_taoChanging(string value);
    partial void Onnguoi_taoChanged();
    #endregion
		
		public xuat_kho()
		{
			this._xuat_kho_cts = new EntitySet<xuat_kho_ct>(new Action<xuat_kho_ct>(this.attach_xuat_kho_cts), new Action<xuat_kho_ct>(this.detach_xuat_kho_cts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loat_xuat", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string loat_xuat
		{
			get
			{
				return this._loat_xuat;
			}
			set
			{
				if ((this._loat_xuat != value))
				{
					this.Onloat_xuatChanging(value);
					this.SendPropertyChanging();
					this._loat_xuat = value;
					this.SendPropertyChanged("loat_xuat");
					this.Onloat_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_xuat", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_xuat
		{
			get
			{
				return this._ngay_xuat;
			}
			set
			{
				if ((this._ngay_xuat != value))
				{
					this.Onngay_xuatChanging(value);
					this.SendPropertyChanging();
					this._ngay_xuat = value;
					this.SendPropertyChanged("ngay_xuat");
					this.Onngay_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhan_vien_id", DbType="Int NOT NULL")]
		public int nhan_vien_id
		{
			get
			{
				return this._nhan_vien_id;
			}
			set
			{
				if ((this._nhan_vien_id != value))
				{
					this.Onnhan_vien_idChanging(value);
					this.SendPropertyChanging();
					this._nhan_vien_id = value;
					this.SendPropertyChanged("nhan_vien_id");
					this.Onnhan_vien_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_hoa_don", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ma_hoa_don
		{
			get
			{
				return this._ma_hoa_don;
			}
			set
			{
				if ((this._ma_hoa_don != value))
				{
					this.Onma_hoa_donChanging(value);
					this.SendPropertyChanging();
					this._ma_hoa_don = value;
					this.SendPropertyChanged("ma_hoa_don");
					this.Onma_hoa_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_san_pham", DbType="Int NOT NULL")]
		public int sl_san_pham
		{
			get
			{
				return this._sl_san_pham;
			}
			set
			{
				if ((this._sl_san_pham != value))
				{
					this.Onsl_san_phamChanging(value);
					this.SendPropertyChanging();
					this._sl_san_pham = value;
					this.SendPropertyChanged("sl_san_pham");
					this.Onsl_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_xuat", DbType="Int NOT NULL")]
		public int sl_xuat
		{
			get
			{
				return this._sl_xuat;
			}
			set
			{
				if ((this._sl_xuat != value))
				{
					this.Onsl_xuatChanging(value);
					this.SendPropertyChanging();
					this._sl_xuat = value;
					this.SendPropertyChanged("sl_xuat");
					this.Onsl_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noi_dung_xuat", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string noi_dung_xuat
		{
			get
			{
				return this._noi_dung_xuat;
			}
			set
			{
				if ((this._noi_dung_xuat != value))
				{
					this.Onnoi_dung_xuatChanging(value);
					this.SendPropertyChanging();
					this._noi_dung_xuat = value;
					this.SendPropertyChanged("noi_dung_xuat");
					this.Onnoi_dung_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_tao", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nguoi_tao
		{
			get
			{
				return this._nguoi_tao;
			}
			set
			{
				if ((this._nguoi_tao != value))
				{
					this.Onnguoi_taoChanging(value);
					this.SendPropertyChanging();
					this._nguoi_tao = value;
					this.SendPropertyChanged("nguoi_tao");
					this.Onnguoi_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="xuat_kho_xuat_kho_ct", Storage="_xuat_kho_cts", ThisKey="id", OtherKey="xuat_kho_id")]
		public EntitySet<xuat_kho_ct> xuat_kho_cts
		{
			get
			{
				return this._xuat_kho_cts;
			}
			set
			{
				this._xuat_kho_cts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_xuat_kho_cts(xuat_kho_ct entity)
		{
			this.SendPropertyChanging();
			entity.xuat_kho = this;
		}
		
		private void detach_xuat_kho_cts(xuat_kho_ct entity)
		{
			this.SendPropertyChanging();
			entity.xuat_kho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.san_pham")]
	public partial class san_pham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten_san_pham;
		
		private string _hien_thi;
		
		private string _nhom_san_pham;
		
		private string _hang_sx;
		
		private string _hinh_anh;
		
		private string _dia_chi;
		
		private string _thong_tin;
		
		private System.DateTime _han_su_dung;
		
		private string _quy_cach;
		
		private string _dvt;
		
		private double _gia_nhap;
		
		private int _sl_toi_thieu;
		
		private int _sl_toi_da;
		
		private int _sl_nhap;
		
		private int _sl_xuat;
		
		private int _sl_ton;
		
		private string _trang_thai;
		
		private string _ghi_chu;
		
		private System.DateTime _ngay_tao;
		
		private System.DateTime _ngay_cap_nhat;
		
		private string _nguoi_tao;
		
		private EntitySet<nhap_kho_ct> _nhap_kho_cts;
		
		private EntitySet<xuat_kho_ct> _xuat_kho_cts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onten_san_phamChanging(string value);
    partial void Onten_san_phamChanged();
    partial void Onhien_thiChanging(string value);
    partial void Onhien_thiChanged();
    partial void Onnhom_san_phamChanging(string value);
    partial void Onnhom_san_phamChanged();
    partial void Onhang_sxChanging(string value);
    partial void Onhang_sxChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Onthong_tinChanging(string value);
    partial void Onthong_tinChanged();
    partial void Onhan_su_dungChanging(System.DateTime value);
    partial void Onhan_su_dungChanged();
    partial void Onquy_cachChanging(string value);
    partial void Onquy_cachChanged();
    partial void OndvtChanging(string value);
    partial void OndvtChanged();
    partial void Ongia_nhapChanging(double value);
    partial void Ongia_nhapChanged();
    partial void Onsl_toi_thieuChanging(int value);
    partial void Onsl_toi_thieuChanged();
    partial void Onsl_toi_daChanging(int value);
    partial void Onsl_toi_daChanged();
    partial void Onsl_nhapChanging(int value);
    partial void Onsl_nhapChanged();
    partial void Onsl_xuatChanging(int value);
    partial void Onsl_xuatChanged();
    partial void Onsl_tonChanging(int value);
    partial void Onsl_tonChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.DateTime value);
    partial void Onngay_cap_nhatChanged();
    partial void Onnguoi_taoChanging(string value);
    partial void Onnguoi_taoChanged();
    #endregion
		
		public san_pham()
		{
			this._nhap_kho_cts = new EntitySet<nhap_kho_ct>(new Action<nhap_kho_ct>(this.attach_nhap_kho_cts), new Action<nhap_kho_ct>(this.detach_nhap_kho_cts));
			this._xuat_kho_cts = new EntitySet<xuat_kho_ct>(new Action<xuat_kho_ct>(this.attach_xuat_kho_cts), new Action<xuat_kho_ct>(this.detach_xuat_kho_cts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_san_pham", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_san_pham
		{
			get
			{
				return this._ten_san_pham;
			}
			set
			{
				if ((this._ten_san_pham != value))
				{
					this.Onten_san_phamChanging(value);
					this.SendPropertyChanging();
					this._ten_san_pham = value;
					this.SendPropertyChanged("ten_san_pham");
					this.Onten_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hien_thi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string hien_thi
		{
			get
			{
				return this._hien_thi;
			}
			set
			{
				if ((this._hien_thi != value))
				{
					this.Onhien_thiChanging(value);
					this.SendPropertyChanging();
					this._hien_thi = value;
					this.SendPropertyChanged("hien_thi");
					this.Onhien_thiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhom_san_pham", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nhom_san_pham
		{
			get
			{
				return this._nhom_san_pham;
			}
			set
			{
				if ((this._nhom_san_pham != value))
				{
					this.Onnhom_san_phamChanging(value);
					this.SendPropertyChanging();
					this._nhom_san_pham = value;
					this.SendPropertyChanged("nhom_san_pham");
					this.Onnhom_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hang_sx", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string hang_sx
		{
			get
			{
				return this._hang_sx;
			}
			set
			{
				if ((this._hang_sx != value))
				{
					this.Onhang_sxChanging(value);
					this.SendPropertyChanging();
					this._hang_sx = value;
					this.SendPropertyChanged("hang_sx");
					this.Onhang_sxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="NVarChar(255)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thong_tin", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string thong_tin
		{
			get
			{
				return this._thong_tin;
			}
			set
			{
				if ((this._thong_tin != value))
				{
					this.Onthong_tinChanging(value);
					this.SendPropertyChanging();
					this._thong_tin = value;
					this.SendPropertyChanged("thong_tin");
					this.Onthong_tinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_han_su_dung", DbType="DateTime NOT NULL")]
		public System.DateTime han_su_dung
		{
			get
			{
				return this._han_su_dung;
			}
			set
			{
				if ((this._han_su_dung != value))
				{
					this.Onhan_su_dungChanging(value);
					this.SendPropertyChanging();
					this._han_su_dung = value;
					this.SendPropertyChanged("han_su_dung");
					this.Onhan_su_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quy_cach", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string quy_cach
		{
			get
			{
				return this._quy_cach;
			}
			set
			{
				if ((this._quy_cach != value))
				{
					this.Onquy_cachChanging(value);
					this.SendPropertyChanging();
					this._quy_cach = value;
					this.SendPropertyChanged("quy_cach");
					this.Onquy_cachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dvt", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string dvt
		{
			get
			{
				return this._dvt;
			}
			set
			{
				if ((this._dvt != value))
				{
					this.OndvtChanging(value);
					this.SendPropertyChanging();
					this._dvt = value;
					this.SendPropertyChanged("dvt");
					this.OndvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_nhap", DbType="Float NOT NULL")]
		public double gia_nhap
		{
			get
			{
				return this._gia_nhap;
			}
			set
			{
				if ((this._gia_nhap != value))
				{
					this.Ongia_nhapChanging(value);
					this.SendPropertyChanging();
					this._gia_nhap = value;
					this.SendPropertyChanged("gia_nhap");
					this.Ongia_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_toi_thieu", DbType="Int NOT NULL")]
		public int sl_toi_thieu
		{
			get
			{
				return this._sl_toi_thieu;
			}
			set
			{
				if ((this._sl_toi_thieu != value))
				{
					this.Onsl_toi_thieuChanging(value);
					this.SendPropertyChanging();
					this._sl_toi_thieu = value;
					this.SendPropertyChanged("sl_toi_thieu");
					this.Onsl_toi_thieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_toi_da", DbType="Int NOT NULL")]
		public int sl_toi_da
		{
			get
			{
				return this._sl_toi_da;
			}
			set
			{
				if ((this._sl_toi_da != value))
				{
					this.Onsl_toi_daChanging(value);
					this.SendPropertyChanging();
					this._sl_toi_da = value;
					this.SendPropertyChanged("sl_toi_da");
					this.Onsl_toi_daChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_nhap", DbType="Int NOT NULL")]
		public int sl_nhap
		{
			get
			{
				return this._sl_nhap;
			}
			set
			{
				if ((this._sl_nhap != value))
				{
					this.Onsl_nhapChanging(value);
					this.SendPropertyChanging();
					this._sl_nhap = value;
					this.SendPropertyChanged("sl_nhap");
					this.Onsl_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_xuat", DbType="Int NOT NULL")]
		public int sl_xuat
		{
			get
			{
				return this._sl_xuat;
			}
			set
			{
				if ((this._sl_xuat != value))
				{
					this.Onsl_xuatChanging(value);
					this.SendPropertyChanging();
					this._sl_xuat = value;
					this.SendPropertyChanged("sl_xuat");
					this.Onsl_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_ton", DbType="Int NOT NULL")]
		public int sl_ton
		{
			get
			{
				return this._sl_ton;
			}
			set
			{
				if ((this._sl_ton != value))
				{
					this.Onsl_tonChanging(value);
					this.SendPropertyChanging();
					this._sl_ton = value;
					this.SendPropertyChanged("sl_ton");
					this.Onsl_tonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_tao", DbType="NVarChar(255)")]
		public string nguoi_tao
		{
			get
			{
				return this._nguoi_tao;
			}
			set
			{
				if ((this._nguoi_tao != value))
				{
					this.Onnguoi_taoChanging(value);
					this.SendPropertyChanging();
					this._nguoi_tao = value;
					this.SendPropertyChanged("nguoi_tao");
					this.Onnguoi_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_nhap_kho_ct", Storage="_nhap_kho_cts", ThisKey="id", OtherKey="san_pham_id")]
		public EntitySet<nhap_kho_ct> nhap_kho_cts
		{
			get
			{
				return this._nhap_kho_cts;
			}
			set
			{
				this._nhap_kho_cts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_xuat_kho_ct", Storage="_xuat_kho_cts", ThisKey="id", OtherKey="san_pham_id")]
		public EntitySet<xuat_kho_ct> xuat_kho_cts
		{
			get
			{
				return this._xuat_kho_cts;
			}
			set
			{
				this._xuat_kho_cts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhap_kho_cts(nhap_kho_ct entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_nhap_kho_cts(nhap_kho_ct entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
		
		private void attach_xuat_kho_cts(xuat_kho_ct entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_xuat_kho_cts(xuat_kho_ct entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thong_tin_cty")]
	public partial class thong_tin_cty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten_cty;
		
		private string _ten_day_du;
		
		private string _nguoi_dai_dien;
		
		private string _dia_chi;
		
		private string _sdt;
		
		private string _email;
		
		private string _website;
		
		private System.DateTime _ngay_tao;
		
		private System.DateTime _ngay_update;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onten_ctyChanging(string value);
    partial void Onten_ctyChanged();
    partial void Onten_day_duChanging(string value);
    partial void Onten_day_duChanged();
    partial void Onnguoi_dai_dienChanging(string value);
    partial void Onnguoi_dai_dienChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_updateChanging(System.DateTime value);
    partial void Onngay_updateChanged();
    #endregion
		
		public thong_tin_cty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_cty", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_cty
		{
			get
			{
				return this._ten_cty;
			}
			set
			{
				if ((this._ten_cty != value))
				{
					this.Onten_ctyChanging(value);
					this.SendPropertyChanging();
					this._ten_cty = value;
					this.SendPropertyChanged("ten_cty");
					this.Onten_ctyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_day_du", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_day_du
		{
			get
			{
				return this._ten_day_du;
			}
			set
			{
				if ((this._ten_day_du != value))
				{
					this.Onten_day_duChanging(value);
					this.SendPropertyChanging();
					this._ten_day_du = value;
					this.SendPropertyChanged("ten_day_du");
					this.Onten_day_duChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dai_dien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nguoi_dai_dien
		{
			get
			{
				return this._nguoi_dai_dien;
			}
			set
			{
				if ((this._nguoi_dai_dien != value))
				{
					this.Onnguoi_dai_dienChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dai_dien = value;
					this.SendPropertyChanged("nguoi_dai_dien");
					this.Onnguoi_dai_dienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_update", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_update
		{
			get
			{
				return this._ngay_update;
			}
			set
			{
				if ((this._ngay_update != value))
				{
					this.Onngay_updateChanging(value);
					this.SendPropertyChanging();
					this._ngay_update = value;
					this.SendPropertyChanged("ngay_update");
					this.Onngay_updateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xuat_kho_ct")]
	public partial class xuat_kho_ct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _LoaiXuat;
		
		private int _xuat_kho_id;
		
		private System.DateTime _ngay_xuat;
		
		private int _san_pham_id;
		
		private string _ten_san_pham;
		
		private string _nhom_san_pham;
		
		private string _hang_sx;
		
		private string _hinh_anh;
		
		private string _thong_tin;
		
		private string _quy_cach;
		
		private string _dvt;
		
		private string _so_lo;
		
		private System.DateTime _ngay_het_han;
		
		private int _sl_xuat;
		
		private int _sl_xuat_tong;
		
		private System.DateTime _ngay_tao;
		
		private System.DateTime _ngay_cap_nhat;
		
		private string _nguoi_tao;
		
		private EntityRef<san_pham> _san_pham;
		
		private EntityRef<xuat_kho> _xuat_kho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnLoaiXuatChanging(string value);
    partial void OnLoaiXuatChanged();
    partial void Onxuat_kho_idChanging(int value);
    partial void Onxuat_kho_idChanged();
    partial void Onngay_xuatChanging(System.DateTime value);
    partial void Onngay_xuatChanged();
    partial void Onsan_pham_idChanging(int value);
    partial void Onsan_pham_idChanged();
    partial void Onten_san_phamChanging(string value);
    partial void Onten_san_phamChanged();
    partial void Onnhom_san_phamChanging(string value);
    partial void Onnhom_san_phamChanged();
    partial void Onhang_sxChanging(string value);
    partial void Onhang_sxChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    partial void Onthong_tinChanging(string value);
    partial void Onthong_tinChanged();
    partial void Onquy_cachChanging(string value);
    partial void Onquy_cachChanged();
    partial void OndvtChanging(string value);
    partial void OndvtChanged();
    partial void Onso_loChanging(string value);
    partial void Onso_loChanged();
    partial void Onngay_het_hanChanging(System.DateTime value);
    partial void Onngay_het_hanChanged();
    partial void Onsl_xuatChanging(int value);
    partial void Onsl_xuatChanged();
    partial void Onsl_xuat_tongChanging(int value);
    partial void Onsl_xuat_tongChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.DateTime value);
    partial void Onngay_cap_nhatChanged();
    partial void Onnguoi_taoChanging(string value);
    partial void Onnguoi_taoChanged();
    #endregion
		
		public xuat_kho_ct()
		{
			this._san_pham = default(EntityRef<san_pham>);
			this._xuat_kho = default(EntityRef<xuat_kho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiXuat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LoaiXuat
		{
			get
			{
				return this._LoaiXuat;
			}
			set
			{
				if ((this._LoaiXuat != value))
				{
					this.OnLoaiXuatChanging(value);
					this.SendPropertyChanging();
					this._LoaiXuat = value;
					this.SendPropertyChanged("LoaiXuat");
					this.OnLoaiXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuat_kho_id", DbType="Int NOT NULL")]
		public int xuat_kho_id
		{
			get
			{
				return this._xuat_kho_id;
			}
			set
			{
				if ((this._xuat_kho_id != value))
				{
					if (this._xuat_kho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onxuat_kho_idChanging(value);
					this.SendPropertyChanging();
					this._xuat_kho_id = value;
					this.SendPropertyChanged("xuat_kho_id");
					this.Onxuat_kho_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_xuat", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_xuat
		{
			get
			{
				return this._ngay_xuat;
			}
			set
			{
				if ((this._ngay_xuat != value))
				{
					this.Onngay_xuatChanging(value);
					this.SendPropertyChanging();
					this._ngay_xuat = value;
					this.SendPropertyChanged("ngay_xuat");
					this.Onngay_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="Int NOT NULL")]
		public int san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_san_pham", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_san_pham
		{
			get
			{
				return this._ten_san_pham;
			}
			set
			{
				if ((this._ten_san_pham != value))
				{
					this.Onten_san_phamChanging(value);
					this.SendPropertyChanging();
					this._ten_san_pham = value;
					this.SendPropertyChanged("ten_san_pham");
					this.Onten_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhom_san_pham", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nhom_san_pham
		{
			get
			{
				return this._nhom_san_pham;
			}
			set
			{
				if ((this._nhom_san_pham != value))
				{
					this.Onnhom_san_phamChanging(value);
					this.SendPropertyChanging();
					this._nhom_san_pham = value;
					this.SendPropertyChanged("nhom_san_pham");
					this.Onnhom_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hang_sx", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string hang_sx
		{
			get
			{
				return this._hang_sx;
			}
			set
			{
				if ((this._hang_sx != value))
				{
					this.Onhang_sxChanging(value);
					this.SendPropertyChanging();
					this._hang_sx = value;
					this.SendPropertyChanged("hang_sx");
					this.Onhang_sxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thong_tin", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string thong_tin
		{
			get
			{
				return this._thong_tin;
			}
			set
			{
				if ((this._thong_tin != value))
				{
					this.Onthong_tinChanging(value);
					this.SendPropertyChanging();
					this._thong_tin = value;
					this.SendPropertyChanged("thong_tin");
					this.Onthong_tinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quy_cach", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string quy_cach
		{
			get
			{
				return this._quy_cach;
			}
			set
			{
				if ((this._quy_cach != value))
				{
					this.Onquy_cachChanging(value);
					this.SendPropertyChanging();
					this._quy_cach = value;
					this.SendPropertyChanged("quy_cach");
					this.Onquy_cachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dvt", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string dvt
		{
			get
			{
				return this._dvt;
			}
			set
			{
				if ((this._dvt != value))
				{
					this.OndvtChanging(value);
					this.SendPropertyChanging();
					this._dvt = value;
					this.SendPropertyChanged("dvt");
					this.OndvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_lo", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string so_lo
		{
			get
			{
				return this._so_lo;
			}
			set
			{
				if ((this._so_lo != value))
				{
					this.Onso_loChanging(value);
					this.SendPropertyChanging();
					this._so_lo = value;
					this.SendPropertyChanged("so_lo");
					this.Onso_loChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_het_han", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_het_han
		{
			get
			{
				return this._ngay_het_han;
			}
			set
			{
				if ((this._ngay_het_han != value))
				{
					this.Onngay_het_hanChanging(value);
					this.SendPropertyChanging();
					this._ngay_het_han = value;
					this.SendPropertyChanged("ngay_het_han");
					this.Onngay_het_hanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_xuat", DbType="Int NOT NULL")]
		public int sl_xuat
		{
			get
			{
				return this._sl_xuat;
			}
			set
			{
				if ((this._sl_xuat != value))
				{
					this.Onsl_xuatChanging(value);
					this.SendPropertyChanging();
					this._sl_xuat = value;
					this.SendPropertyChanged("sl_xuat");
					this.Onsl_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_xuat_tong", DbType="Int NOT NULL")]
		public int sl_xuat_tong
		{
			get
			{
				return this._sl_xuat_tong;
			}
			set
			{
				if ((this._sl_xuat_tong != value))
				{
					this.Onsl_xuat_tongChanging(value);
					this.SendPropertyChanging();
					this._sl_xuat_tong = value;
					this.SendPropertyChanged("sl_xuat_tong");
					this.Onsl_xuat_tongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_tao", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string nguoi_tao
		{
			get
			{
				return this._nguoi_tao;
			}
			set
			{
				if ((this._nguoi_tao != value))
				{
					this.Onnguoi_taoChanging(value);
					this.SendPropertyChanging();
					this._nguoi_tao = value;
					this.SendPropertyChanged("nguoi_tao");
					this.Onnguoi_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_xuat_kho_ct", Storage="_san_pham", ThisKey="san_pham_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.xuat_kho_cts.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.xuat_kho_cts.Add(this);
						this._san_pham_id = value.id;
					}
					else
					{
						this._san_pham_id = default(int);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="xuat_kho_xuat_kho_ct", Storage="_xuat_kho", ThisKey="xuat_kho_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public xuat_kho xuat_kho
		{
			get
			{
				return this._xuat_kho.Entity;
			}
			set
			{
				xuat_kho previousValue = this._xuat_kho.Entity;
				if (((previousValue != value) 
							|| (this._xuat_kho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._xuat_kho.Entity = null;
						previousValue.xuat_kho_cts.Remove(this);
					}
					this._xuat_kho.Entity = value;
					if ((value != null))
					{
						value.xuat_kho_cts.Add(this);
						this._xuat_kho_id = value.id;
					}
					else
					{
						this._xuat_kho_id = default(int);
					}
					this.SendPropertyChanged("xuat_kho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
